# Generated by Django 6.1 on 2026-09-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('brand_model', models.CharField(max_length=100)),
                ('key_code', models.CharField(max_length=20)),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('responsible', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('En Custodia', 'En Custodia'), ('Devuelto', 'Devuelto')], default='En Custodia', max_length=20)),
                ('parking_spot', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
